Repository Wanadian/stock_market_app, pull requests merged in 2023-09, with the labels that each got.

#3 Feat(project) : initiate important files and clean up
  README.md
  analysis_options.yaml
  lib/classes/accountInformation.dart
  lib/classes/wallet.dart
  lib/context/wallet/inheritedWallet.dart
  lib/context/wallet/rootWallet.dart
  lib/data/data.json
  lib/main.dart
  lib/screens/accountBalance.dart
  lib/screens/creditCard.dart
  lib/screens/stockMarket.dart
  lib/screens/stockPurchased.dart
  lib/screens/wallet.dart
  lib/utils/types.dart
  lib/widgets/buttonWidget.dart
  lib/widgets/inputWidget.dart
  lib/widgets/stockInformation.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation, enhancement, feature

#5 docs(readme): readme initialised
  README.md
Labels: documentation

#4 feat(splash-screen): splash screen added
  lib/main.dart
  lib/screens/splashScreen.dart
Labels: feature, design

#6 feat(button widget): new widget
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/widgets/buttonWidget.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, design

#8 fix(button widget): color
  lib/widgets/buttonWidget.dart
Labels: bug, design

#7 Feat(share banner): new widget
  lib/widgets/shareBannerWidget.dart
  lib/widgets/stockInformation.dart
Labels: feature, design

#9 Feat(balance screen): new balance
  assets/closed_safe.png
  assets/open_safe.png
  lib/main.dart
  lib/screens/accountBalance.dart
  lib/screens/balance.dart
  lib/screens/modifyBalance.dart
  lib/screens/purchasedShares.dart
  lib/screens/splashScreen.dart
  lib/screens/stockPurchased.dart
  lib/screens/wallet.dart
  lib/widgets/buttonWidget.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, design

#15 Use of Firebase and Share service and repository added
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java
  android/build.gradle
  ios/Podfile
  ios/Runner/GoogleService-Info.plist
  ios/firebase_app_id_file.json
  lib/classes/share.dart
  lib/classes/symbol.dart
  lib/context/inheritedServices.dart
  lib/context/inheritedSymbolService.dart
  lib/context/rootWidget.dart
  lib/data/symbols.json
  lib/errors/shareError.dart
  lib/errors/symbolError.dart
  lib/firebase_options.dart
  lib/main.dart
  lib/repositories/shareRepository.dart
  lib/repositories/symbolRepository.dart
  lib/services/shareService.dart
  lib/services/symbolService.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: documentation, feature, data treatment

#16 Feat (form & modifyBalance): adding formWidget and modifyBalance screen
  lib/main.dart
  lib/screens/balance.dart
  lib/screens/modifyBalance.dart
  lib/widgets/form/fields/dateFieldWidget.dart
  lib/widgets/form/fields/numberFieldWidget.dart
  lib/widgets/form/fields/textFieldWidget.dart
  lib/widgets/form/formWidget.dart
  lib/widgets/inputWidget.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, design

#17 Feature user's shares and clean code
  lib/classes/accountInformation.dart
  lib/context/inheritedServices.dart
  lib/context/rootWidget.dart
  lib/entities/share.dart
  lib/entities/symbol.dart
  lib/entities/userShares.dart
  lib/entities/wallet.dart
  lib/errors/userShareError.dart
  lib/repositories/shareRepository.dart
  lib/repositories/symbolRepository.dart
  lib/repositories/userSharesRepository.dart
  lib/services/shareService.dart
  lib/services/symbolService.dart
  lib/services/userSharesService.dart
Labels: documentation, feature, data treatment
