Repository Wanadian/stock_market_app, pull requests merged in 2023-10, with the labels that each got.

#18 Change the api endpoint
  lib/context/rootWidget.dart
  lib/entities/share.dart
  lib/repositories/shareRepository.dart
  lib/services/shareService.dart
Labels: feature, data treatment

#19 fix(sharBannerWidget/style): style
  lib/screens/stock-market/tabs/purchasedShares.dart
  lib/widgets/shareBannerWidget.dart
Labels: enhancement, design

#20 feat(Graph): new screen
  lib/screens/graph.dart
  lib/screens/stock-market/tabs/purchasedShares.dart
  lib/screens/stock-market/tabs/stockMarket.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, design

#21 Shares prices and history
  lib/entities/shareEntity.dart
  lib/entities/symbolEntity.dart
  lib/entities/userSharesEntity.dart
  lib/entities/wallet.dart
  lib/entities/walletEntity.dart
  lib/repositories/shareRepository.dart
  lib/repositories/symbolRepository.dart
  lib/repositories/userSharesRepository.dart
  lib/services/shareService.dart
  lib/services/userSharesService.dart
Labels: bug, documentation, feature, data treatment

#22 Deletes user shares if the nb shares is equal to 0
  lib/services/userSharesService.dart
Labels: bug

#25 feat(shareBannerWidget): variation backend call
  lib/widgets/shareBannerWidget.dart
Labels: enhancement, feature

#26 Addition of wallet and cards
  lib/context/inheritedServices.dart
  lib/context/rootWidget.dart
  lib/entities/cardEntity.dart
  lib/entities/walletEntity.dart
  lib/errors/cardError.dart
  lib/errors/shareError.dart
  lib/errors/symbolError.dart
  lib/errors/userShareError.dart
  lib/errors/walletError.dart
  lib/main.dart
  lib/repositories/cardRepository.dart
  lib/repositories/shareRepository.dart
  lib/repositories/symbolRepository.dart
  lib/repositories/userSharesRepository.dart
  lib/repositories/walletRepository.dart
  lib/services/cardService.dart
  lib/services/shareService.dart
  lib/services/userSharesService.dart
  lib/services/walletService.dart
  lib/utils/types.dart
Labels: documentation, feature, data treatment

#27 Fix/project/design
  assets/closed_safe.png
  assets/coins.png
  assets/money-bag.png
  assets/money.png
  assets/open_safe.png
  assets/wallet.png
  lib/screens/balance.dart
  lib/screens/graph.dart
  lib/widgets/shareBannerWidget.dart
Labels: enhancement, design

#28 Adds a method to the service to get all the wallet object
  lib/repositories/walletRepository.dart
  lib/services/userSharesService.dart
  lib/services/walletService.dart
Labels: bug, feature

#29 feat(project): balance backend calls
  lib/screens/balance.dart
  lib/screens/modifyBalance.dart
  lib/screens/stock-market/stockMarketAppBar.dart
Labels: enhancement, data treatment

#30 Fix(modifyBalance): global keys reused issue
  lib/screens/modifyBalance.dart
  lib/widgets/form/fields/dateFieldWidget.dart
  lib/widgets/form/fields/numberFieldWidget.dart
  lib/widgets/form/fields/textFieldWidget.dart
  lib/widgets/form/formWidget.dart
Labels: bug

#31 Adds method credit balance with int value
  lib/services/userSharesService.dart
  lib/services/walletService.dart
Labels: bug, feature

#32 Fix the balance in double value and fix the debit wallet balance method
  lib/entities/walletEntity.dart
  lib/services/walletService.dart
Labels: bug

#33 Feat/credit card
  lib/screens/creditCard.dart
  lib/screens/modifyBalance.dart
  lib/screens/newCreditCard.dart
  lib/screens/paymentMethode.dart
  lib/screens/savedCreditCards.dart
  lib/widgets/buttonWidget.dart
  lib/widgets/form/fields/dropdownInputWidget.dart
Labels: enhancement, feature, design, data treatment

#34 fix(paymentMethode): deactivate button when no card saved
  lib/screens/modifyBalance.dart
  lib/screens/newCreditCard.dart
  lib/screens/paymentMethod.dart
  lib/screens/savedCreditCards.dart
  lib/widgets/buttonWidget.dart
Labels: bug

#35 feat(stock market): new way to deal with shares and transactions
  lib/screens/stock-market/tabs/purchasedShares.dart
  lib/screens/stock-market/tabs/stockMarket.dart
  lib/widgets/shareBannerWidget.dart
Labels: bug, enhancement, data treatment

#37 Fix/stock market/purchasing without funds issue
  lib/screens/stock-market/tabs/purchasedShares.dart
  lib/widgets/buttonWidget.dart
  lib/widgets/shareBannerWidget.dart
Labels: bug, data treatment

#36 feat(deleteCreditCard): new page
  lib/screens/deleteCreditCard.dart
  lib/screens/savedCreditCards.dart
  lib/widgets/form/fields/dropdownInputWidget.dart
Labels: feature, design, data treatment

#38 fix return type repositories and debit wallet balance function
  lib/repositories/cardRepository.dart
  lib/repositories/shareRepository.dart
  lib/repositories/symbolRepository.dart
  lib/repositories/userSharesRepository.dart
  lib/services/walletService.dart
Labels: bug

#39 Fix/stock market/spam purchase issue
  lib/screens/stock-market/tabs/purchasedShares.dart
  lib/screens/stock-market/tabs/stockMarket.dart
  lib/widgets/buttonWidget.dart
Labels: bug, enhancement, design, data treatment

#40 Fix the type of price in ShareEntity in double
  lib/entities/shareEntity.dart
Labels: bug

#41 fix(reload balance): workaround
  lib/screens/newCreditCard.dart
  lib/screens/savedCreditCards.dart
  lib/screens/stock-market/tabs/stockMarket.dart
Labels: bug

#43 fix(balance-estimation): adds method which return the string value of…
  lib/services/userSharesService.dart
Labels: data treatment

#44 Fix(project): refactoring code
  lib/screens/balance.dart
  lib/screens/deleteCreditCard.dart
  lib/screens/graph.dart
  lib/screens/modifyBalance.dart
  lib/screens/newCreditCard.dart
  lib/screens/paymentMethod.dart
  lib/screens/savedCreditCards.dart
  lib/screens/stock-market/stockMarketAppBar.dart
  lib/screens/stock-market/tabs/purchasedShares.dart
  lib/screens/stock-market/tabs/stockMarket.dart
  lib/widgets/form/fields/dateFieldWidget.dart
  lib/widgets/form/fields/dropdownFieldWidget.dart
  lib/widgets/form/fields/numberFieldWidget.dart
  lib/widgets/form/fields/textFieldWidget.dart
  lib/widgets/form/formWidget.dart
  lib/widgets/shareBannerWidget.dart
Labels: bug, enhancement, design, data treatment

#45 Completes the readme (in general and back side)
  README.md
Labels: documentation

#48 fix(project): minor changes
  lib/screens/newCreditCard.dart
  lib/screens/savedCreditCards.dart
  lib/widgets/displayBalanceWidget.dart
Labels: bug

#49 Fix/stock market/refresh bug
  lib/screens/stock-market/stockMarketAppBar.dart
  lib/screens/stock-market/tabs/purchasedShares.dart
  lib/screens/stock-market/tabs/stockMarket.dart
Labels: bug

#50 azddbaziuq
  README.md
Labels: documentation

#51 Completes the readme
  README.md
Labels: documentation

#52 Completes the readme
  README.md
Labels: documentation

#54 Fix purchased shares list
  lib/screens/stock-market/tabs/purchasedShares.dart
Labels: bug

#55 Fix the list of purchased shares
  lib/screens/stock-market/tabs/purchasedShares.dart
Labels: bug

#56 Adds comments
  lib/dto/shareDto.dart
  lib/dto/shareHistoryDataDto.dart
  lib/screens/stock-market/stockMarketAppBar.dart
Labels: documentation

#57 Adds comments
  lib/dto/shareDto.dart
  lib/dto/shareHistoryDataDto.dart
  lib/screens/stock-market/stockMarketAppBar.dart
Labels: documentation

#58 Completes readme
  README.md
Labels: documentation
